<?php

namespace Database\Seeders;

use App\Models\Mishap;
use Illuminate\Database\Seeder;

/**
 * Imports the 6 Corrective Action Plans from CAPS.xlsx and attaches each to its
 * existing mishap (matched by date + a description keyword). Idempotent: a
 * mishap's plan is replaced on re-seed. A plan whose mishap is not found is
 * skipped and reported (e.g. the MPV vehicular, not yet a record).
 */
class CorrectiveActionSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->plans() as $pl) {
            $query = Mishap::query();
            if ($pl['date']) {
                $query->whereDate('mishap_date', $pl['date']);
            }
            $mishap = $query->where('description', 'like', '%'.$pl['keyword'].'%')->first();

            if (! $mishap) {
                $this->command?->warn("CAP skipped (no matching mishap): {$pl['title']}");
                continue;
            }

            $mishap->correctiveActions()->delete();
            foreach ($pl['entries'] as $i => $e) {
                $mishap->correctiveActions()->create($e + ['sort_order' => $i]);
            }
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function plans(): array
    {
        return [
            [
                'title' => 'MD-520MG (Wire Strike)',
                'date' => '2026-02-01',
                'keyword' => 'wire strike',
                'entries' => [
                ['latent_condition' => 'The area that covers the approach was not properly cleared of any obstacles of any such as wires and posts', 'category' => null, 'cause_factor' => 'Human (Primary)', 'opr' => '15SW', 'corrective_action' => 'The Wing shall initiate review and updating of the Tactics, Techniques and Procedures (TTPs) on the conduct of the low level and high-level ground attack tactics', 'staff_action' => 'TTPs Workshop for 2nd Quarter CY 2026', 'status' => 'approved', 'remarks' => 'Approved with minor correction on 16 June 2026'],
                ['latent_condition' => 'The absence of a wire strike protection system on the aircraft significantly exacerbated the damage sustained during the wire strike', 'category' => 'Material', 'cause_factor' => 'Human (Primary)', 'opr' => '460AMG', 'corrective_action' => 'The Group shall create a Technical Working Group (TWG) to conduct a feasibility study and evaluation on the installation and integration of a Wire Strike Protection System (WSPS) for applicable rotary-wing aircraft to enhance survivability during low level operations', 'staff_action' => 'Creation of TWG for WSPS Study and Integration 01 March - 30 Sept CY 2026', 'status' => 'ongoing', 'remarks' => 'TWG was created on 22 May 2026 Awaiting quotation from proponents for the integration of WSPS'],
                ['latent_condition' => 'The absence of a wire strike protection system on the aircraft significantly exacerbated the damage sustained during the wire strike', 'category' => 'Material', 'cause_factor' => 'Human (Primary)', 'opr' => '460AMG', 'corrective_action' => 'The Group shall pursue the immediate installation of Garmin GTN 750Xi to all MD-520MG aircraft, as part of the avionics upgrade program, to enhance pilot situational awareness and improve navigation capability through terrain and obstacles such as towers, buildings, cranes, and power lines', 'staff_action' => 'Inclusion in the MD 520MG Avionics Upgrade Program 2nd Quarter CY 2026', 'status' => 'ongoing', 'remarks' => 'Submitted the request for Avionics Upgrade to OA-4 last 30 April 2026. Awaiting fund support'],
                ['latent_condition' => 'Culture- 15SW permits to jibe pilot proficiency flights with the aircraft\'s ECF', 'category' => 'Organization', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '20AS', 'corrective_action' => 'The Squadron shall review and update the SOPs for the conduct of ECF and Proficiency Flight', 'staff_action' => 'SOP Review', 'status' => 'complied', 'remarks' => 'Complied dtd 04 June 2026'],
                ['latent_condition' => 'Culture- 15SW permits to jibe pilot proficiency flights with the aircraft\'s ECF', 'category' => 'Organization', 'cause_factor' => 'Human (Primay)', 'opr' => '18AS', 'corrective_action' => 'Put into record the incident as part of the lessons learned to be considered by the pilots during their pre-flight briefing and mission planning', 'staff_action' => 'Conduct of Squadron Safety Meeting', 'status' => 'complied', 'remarks' => 'Conducted Squadron Safety Meeting last 19 July 2026'],
                ['latent_condition' => 'TOG 8 does not have designated and well-verified area assignments for utilization of rotary air assets for routine maintenance, training and proficiency flights', 'category' => 'Organization', 'cause_factor' => 'Organizational (Contributory)', 'opr' => 'TOWS/TOGS', 'corrective_action' => 'The TOW through TOGSs shall identify safe and secured areas for the conduct of maintenance, training and proficiency flights', 'staff_action' => 'Creation of TWG to Determine and Formalize Deployment Training Areas', 'status' => 'ongoing', 'remarks' => '2nd Quarter CY 2026'],
                ['latent_condition' => 'Culture- TOG 8 does not maintain independent records of NOTAMs or identified hazards within its AOR', 'category' => 'Organization', 'cause_factor' => 'Environmental (Contributory)', 'opr' => 'TOWS/TOGS', 'corrective_action' => 'The TOGs shall compel the pilots of the transiting aircraft and those deployed under their Operational Control to report sightings of hazards situated along their route. Those reports shall form part of the Notice to Airmen (NOTAM) of the Unit, and to utmost concerned flying units must be ensured', 'staff_action' => 'Accomplishment of Operational Hazard Report Improvement on the Implementation of Safety Management Program', 'status' => 'ongoing', 'remarks' => '2nd Quarter CY 2027'],
                ],
            ],
            [
                'title' => 'SF-260TP aircraft with tail Num',
                'date' => '2026-02-12',
                'keyword' => 'scratched wing tip',
                'entries' => [
                ['latent_condition' => 'Bird Hazard -Observed Bird Activity around the Aerodrome', 'category' => null, 'cause_factor' => 'Human (Primary)', 'opr' => '590ABG', 'corrective_action' => 'It is recommended that the Unit ensure sufficient frequency and continuity of pilot proficiency flights to enhance and sustain pilot proficiency, aircraft handling skills, situational awareness, and decision-making capabilities, particularly during critical phases of flight', 'staff_action' => 'Coordinated with the ODO, Air Operations Branch for appropriate action', 'status' => 'ongoing', 'remarks' => 'ETOC: 3rd Quarter CY 2026'],
                ['latent_condition' => 'Areas surrounding Runway 19 revealed extensive vegetation growth which provide favorable conditions for wildlife habitation, including birds and other animals', 'category' => null, 'cause_factor' => 'Human (Contributory)', 'opr' => '590ABG', 'corrective_action' => 'It is recommended that the Wing, in coordination with the 590ABG and the Aerodrome Operations and Safety Offices enhance and strictly implement the Bird and Animal Strike Hazard (BASH) prevention program to effectively reduce wildlife presence within and around the runway environment.', 'staff_action' => 'Coordinated with the 590ABG for appropriate action', 'status' => 'ongoing', 'remarks' => 'ETOC: Quarterly Scheduled/ Programmed'],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Human (Contributory)', 'opr' => '15SW/Squadron', 'corrective_action' => 'It is recommended that the Wing, through coordination with the 590ABG and other relevant external stakeholders and government agencies (such as DENR) beyond the Unit\'s direct control, conduct regular and intesified vegetation management. This includes grass cutting, removal of shrubs and trimming/removal of trees within and adjacent to runway strips and approach paths to eliminate conditions that attract birds and other wildlife.', 'staff_action' => null, 'status' => 'pending', 'remarks' => null],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Environmental (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'It is recommended that Standard Operating Procedures (SOPs) be reviewed and updated to clearly define the Supervisor of Flight (SOF)\'s roles and responsibilities in aerodrome operations.', 'staff_action' => 'Creation of Technical Working Group (TWG) to discuss and recommend approprite measures', 'status' => 'ongoing', 'remarks' => 'ETOC: 3rd Quarter CY 2026'],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Environmental (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'The SOF shall maintain continuous oversight of runway and approach path conditions to ensure operational safety. The SOF shall actively detect, assess, and monitor wildlife and other environmental hazards within the aerodrome. The SOF shall ensure prompt coordination with Air Traffic Control (ATC) for the timely dissemination of hazard advisories to aircraft.', 'staff_action' => null, 'status' => 'pending', 'remarks' => null],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Environmental (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'Furthermore, the SOF shall appropriately utilizes available optical aids, such as binoculards, when necessary to enhance visual detection capability, particularly during critical phase of flight.', 'staff_action' => null, 'status' => 'pending', 'remarks' => null],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Organizational (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'It is recommended that Standard Operating Procedures (SOPs) be strengthen to clearly emphasize the Air Traffic Controller\'s (ATC) primary role in maintaining safe, orderly, and efficient air traffic control through effective communication. Visual monitoring shall be performed as a supplementary safety function to support overall situational awareness.', 'staff_action' => 'Coordinated with the 590ABG and formed a review committee to strengthen and clearly defined ATC roles', 'status' => 'ongoing', 'remarks' => 'ETOC: 3rd Quarter CY 2026'],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Organizational (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'ATC personnel shall conduct continuous scanning of the runway, approach path, and touchdown zones to support hazard awareness. They shall identify and assess potential hazards, including bird activity and other environmental threats within the aerodrome. ATC shall provide timely, accurate, and concise advisories to inbound and landing aircraft to enhance pilot-decision making.', 'staff_action' => null, 'status' => 'pending', 'remarks' => null],
                ['latent_condition' => 'Reduced Pilot Proficiency affecting response performance and Reduced Operational exposure affecting pilot proficiency', 'category' => 'Organization/Training', 'cause_factor' => 'Organizational (Contributory)', 'opr' => 'Wing', 'corrective_action' => 'ATC shall utilize available optical aids, such as binoculars, when necessary to augment visual capability and improve detection of distant or transient hazards, particularly during critical phases of flight.', 'staff_action' => null, 'status' => 'pending', 'remarks' => null],
                ],
            ],
            [
                'title' => 'MD-520MG (Smash Down)',
                'date' => '2026-02-24',
                'keyword' => 'smash down',
                'entries' => [
                ['latent_condition' => 'Slip - Due to inattention, the pilot did not anticipate the collective loads during the FCF', 'category' => 'Training', 'cause_factor' => 'Human (Primary)', 'opr' => '20AS', 'corrective_action' => 'Review the flight procedures to enhance operational safety. It shall emphasize the "light on skid" phase before the actual hovering to determine possible collective loads before going into the hovering phase', 'staff_action' => 'Conduct of Phase Briefing 2nd Quarter CY 2026', 'status' => 'complied', 'remarks' => 'Complied dtd 18 May 2026 (Added to MD-520MG Checklist, to include updates on Emergency Procedures - Checklist for production)'],
                ['latent_condition' => 'Slip - Due to inattention, the pilot did not anticipate the collective loads during the FCF', 'category' => 'Training', 'cause_factor' => 'Human (Primary)', 'opr' => '20AS', 'corrective_action' => 'Implement semi-annual emergency proficiency flights for all pilots, particularly those who are not instructor pilot-qualified, to ensure continued proficiency in handling abnormal and emergencies. These flights should emphasize proper aircraft control, power management, and recovery techniques during ground maneuvers and hover operations, to enhance pilot capability to effectively arrest rapid or uncontrolled descent at low altitude. The squadron shall review the flight procedures to enhance operational safety', 'staff_action' => 'Conduct of proficiency flights focusing on emergency procedures 2nd Quarter CY 2026', 'status' => 'complied', 'remarks' => 'Complied dtd 10 March 2026 (Proficiency Flights with Instructor Pilots)'],
                ['latent_condition' => 'Culture- The pilot checklist indicates that maneuvers after the N2 Droop Check will follow the Flight Control Response and not the collective load checks. The test pilot performed the collective load check after the N2 droop check, since it was the practice and as he was trained', 'category' => 'Training', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '20AS', 'corrective_action' => 'Review and update the test pilot checklist and test sheet as necessary to follow the reasonable order of maneuvers. 2nd Quarter CY 2026', 'staff_action' => 'Checklist review', 'status' => 'complied', 'remarks' => 'Complied dtd 18 May 2026 (Added to MD-520MG Checklist, to include updates on Emergency Procedures - Checklist for production)'],
                ['latent_condition' => 'Lapse -The MRM was accomplished but it did not indicate the sudden smash down as identified risk', 'category' => 'Training', 'cause_factor' => 'Organizational (Contributory)', 'opr' => 'WSO', 'corrective_action' => 'Conduct a lecture on hazard identification, risk assessment, and proper filling out of the mission risk management form', 'staff_action' => 'Conduct of lecture for the 2nd Quarter CY 2026', 'status' => 'complied', 'remarks' => 'Complied Conducted Lecture last 13 May 2026'],
                ['latent_condition' => 'Culture- The maintenance team performed the After Main Rotor Blade/Drive System Sudden Stoppage - Level 1. The team relies only on their own assessment without approval from a higher authority, whether the special inspection will be elevated to Level 2', 'category' => 'Organization', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '460AMG', 'corrective_action' => 'Create and convene a board to review and deliberate on the results of the scheduled or special inspection conducted prior to the aircraft\'s release for a functional check flight', 'staff_action' => 'Creation of maintenance deliberation board for special inspections', 'status' => 'complied', 'remarks' => 'The Group established the QAI team/branch under the DO,460 in charged with the reviews prior to the conduct of all special inspections. Likewise, an SOP for QAIs stating their duties and responsibilities was crafted and approved and published by the Wing last 12 March 2026'],
                ['latent_condition' => 'Non-standard maintenance practice', 'category' => 'Doctrines', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '462RWFMS', 'corrective_action' => 'Issue a maintenance operating instruction (MOI) directing that the MR hub droop angle check be conducted each time the MR hub is replaced or reinstalled on the MD-520MG helicopter', 'staff_action' => 'Creation of MOI 2nd Quarter 2026', 'status' => 'complied', 'remarks' => 'MR hub droop angle check procedure is already prescribed in the existing MD Helicopters, Inc. Maintenance Manual (Page 608, Revision 37, CSP-HMI-2 [62-20-00]); no separate MOI is required'],
                ['latent_condition' => 'Culture - The maintenance team that conducted the repair of the aircraft after the wire strike was also members of the SIB and FEB', 'category' => 'Organization', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '15SW', 'corrective_action' => 'A maintenance team should also be assigned as a separate composition of investigating teams that focus on the maintenance standard procedures, and to cross check the quality of work the previous maintenance team performed', 'staff_action' => 'Assigning personnel to a specific task to avoid multi-tasking', 'status' => 'as_required', 'remarks' => 'As required'],
                ['latent_condition' => 'Lack of cockpit audio/video recorders', 'category' => 'Material', 'cause_factor' => 'Organizational (Contributory)', 'opr' => '15SW', 'corrective_action' => 'The 15SW shall endeavor to provide cockpit audio/video recorders in its FMC aircraft in aid of any investigation into any incidents. This may also provide clear evidence of any violations and errors that may happen inside the cockpit', 'staff_action' => 'PROG-RAMING/ PROCURE-MEN T OF A VIDEO RECOR-DER', 'status' => 'ongoing', 'remarks' => 'Ongoing'],
                ],
            ],
            [
                'title' => 'Motorcycle traffic incident inv',
                'date' => '2026-01-31',
                'keyword' => 'motorcycle traffic incident',
                'entries' => [
                ['latent_condition' => 'Lack of Adequate Traffic Control Measures, Hazard Mitigation, and Safety Planning', 'category' => 'Materiel', 'cause_factor' => 'Organization', 'opr' => '590ABG/ 15SW', 'corrective_action' => 'Implement a targeted traffic-safety program on the CDO-Airport-Bukidnon Road with high-visibility regulatory and warning signs, electronic speed displays, reflective pavement markings, street lighting, solar-powered flashing beacons at Lumbia Air Base gates, rumble strips, and raised crosswalks or speed tables as needed. Complement these engineering measures with intensified speed enforcement, regular maintenance, a public awareness campaign, and a phased implementation plan with cost estimates and monitoring to quickly reduce speed-related crashes', 'staff_action' => 'Installation of warning signs on both approaches Install LED warning signs, cones, and blinking beacons Conduct public information and advisory campaigns to increase public awareness of the new Airbase Commission of DPWH/ LGU to implement a phased, costed traffic safety upgrade with concurrent enforcement, maintenance, and public-awareness measures', 'status' => 'complied', 'remarks' => 'Complied. Implemented traffic-safety program on the CDO-Airport-Bukidnon Road last 02 February 2026'],
                ['latent_condition' => 'Lack of Adequate Traffic Control Measures, Hazard Mitigation, and Safety Planning', 'category' => 'Materiel', 'cause_factor' => 'Organization', 'opr' => '15SW', 'corrective_action' => 'The Wing should coordinate to 590ABG and LGU\'s for the installation of traffic lights and adequate street lighting at key intersections and known hazard locations along the CDO Airport-Bukidnon Road, plus illuminated warning signs and reflective road markings to improve night visibility and help drivers detect hazards and judge distances. Complement these upgrades with targeted speed-calming measures (rumble strips, reduced speed zones), regular maintenance, and enhanced enforcement to reduce the likelihood of rear end collisions', 'staff_action' => 'Coordination with 590ABG in establishing checkpoints on both sides of the gate with duty personnel to control traffic flow and increase awareness among motorists', 'status' => 'complied', 'remarks' => 'Complied'],
                ['latent_condition' => 'Lack of Adequate Traffic Control Measures, Hazard Mitigation, and Safety Planning', 'category' => 'Training', 'cause_factor' => 'Organization', 'opr' => '15SW', 'corrective_action' => 'Wing, 590ABG to conduct refresher training on defensive riding, hazard recognition, and safe following distances for Wing personnel motorcyclists in the area, emphasizing speed management and proper scanning techniques to improve judgment in low-light and high traffic conditions. Pair this with targeted enforcement of tailgating and speeding laws, plus public awareness campaigns on maintaining safe gaps and anticipating stopped or turning vehicles', 'staff_action' => 'Conduct regular motorcycle safety riding seminars for personnel operators. Wing motorcycle Require completion of a certified riding course and periodic refresher training to maintain skills and safety awareness', 'status' => 'complied', 'remarks' => 'Complied. Conducted Motorcycle Safety Riding Course last 21 May 2026'],
                ],
            ],
            [
                'title' => 'Sheet7',
                'date' => '2026-04-03',
                'keyword' => 'road run',
                'entries' => [
                ['latent_condition' => 'Unsafe Crossing due to obstructed visibility, Exposure to uncontrolled road environment', 'category' => 'Personnel', 'cause_factor' => 'Human (Primary)', 'opr' => '15SW', 'corrective_action' => 'Reiterate to personnel the importance of safety and situational awareness at all times, particularly during physical training activities conducted along public roads. Personnel are likewise reminded to observe traffic conditions, wear appropriate attire and utilize designated safe routes to mitigate risks', 'staff_action' => 'Conduct Safety Briefings', 'status' => 'complied', 'remarks' => 'Conducted Safety Briefings and Implement Buddy System last 30 May 2026'],
                ],
            ],
            [
                'title' => 'Vehicular incindent involving M',
                'date' => null,
                'keyword' => 'SND 3358',
                'entries' => [
                ['latent_condition' => null, 'category' => null, 'cause_factor' => 'Material (Primary)', 'opr' => '15SW', 'corrective_action' => 'Conduct an immediate inspection and compliance review of all assigned government vehicles to determine whether windshield and window tints conform to established safety standards. Vehicles found with excessively dark tinting should be subjected for corrective action, including removal or replacement of tint, to ensure adequate visibility during nighttime and low-light operations', 'staff_action' => null, 'status' => 'pending', 'remarks' => 'Immediately'],
                ],
            ],
        ];
    }
}
